import { Project } from "@/types";

export const sampleProjects: Project[] = [
  {
    id: "1",
    title: "Website Redesign",
    icon: "briefcase-outline",
    color: "#448AFF",
    category: "work",
    priority: "high",
    dueDate: "2026-03-24",
    status: "active",
    createdAt: "2026-01-15",
    tasks: [
      {
        id: "t1",
        title: "Wireframe Homepage",
        description: "",
        completed: true,
      },
      {
        id: "t2",
        title: "Select Color Palette",
        description: "",
        completed: true,
      },
      {
        id: "t3",
        title: "Review Competitors",
        description: "",
        completed: true,
      },
      {
        id: "t4",
        title: "Write Copy for About Page",
        description: "",
        completed: false,
      },
      {
        id: "t5",
        title: "Export Assets",
        description: "Make sure to include SVGs for all icons.",
        completed: false,
      },
      { id: "t6", title: "Final Polish", description: "", completed: false },
      {
        id: "t7",
        title: "Deploy to Production",
        description: "",
        completed: false,
      },
      {
        id: "t8",
        title: "User Acceptance Testing",
        description: "",
        completed: false,
      },
    ],
  },
  {
    id: "2",
    title: "Q3 Financials",
    icon: "cash-multiple",
    color: "#E040FB",
    category: "finance",
    priority: "urgent",
    dueDate: "2026-02-16",
    status: "active",
    createdAt: "2026-01-20",
    tasks: [
      { id: "t9", title: "Collect invoices", description: "", completed: true },
      {
        id: "t10",
        title: "Review expenses",
        description: "",
        completed: false,
      },
      {
        id: "t11",
        title: "Create summary report",
        description: "",
        completed: false,
      },
    ],
  },
  {
    id: "3",
    title: "Fitness Goals",
    icon: "heart-pulse",
    color: "#FF5252",
    category: "health",
    priority: "medium",
    dueDate: "2026-06-01",
    status: "active",
    createdAt: "2026-01-10",
    tasks: [
      {
        id: "t12",
        title: "Plan weekly workouts",
        description: "",
        completed: true,
      },
      {
        id: "t13",
        title: "Track meals for 30 days",
        description: "",
        completed: false,
      },
    ],
  },
  {
    id: "4",
    title: "Japan Trip",
    icon: "airplane",
    color: "#18FFFF",
    category: "travel",
    priority: "low",
    status: "active",
    createdAt: "2026-02-01",
    tasks: [
      { id: "t14", title: "Book flights", description: "", completed: true },
      { id: "t15", title: "Reserve hotels", description: "", completed: true },
      { id: "t16", title: "Plan itinerary", description: "", completed: false },
      {
        id: "t17",
        title: "Get travel insurance",
        description: "",
        completed: false,
      },
    ],
  },
  {
    id: "5",
    title: "Home Renovation",
    icon: "home-outline",
    color: "#FF6E40",
    category: "home",
    priority: "medium",
    status: "on-hold",
    createdAt: "2026-01-05",
    tasks: [
      {
        id: "t18",
        title: "Get contractor quotes",
        description: "",
        completed: true,
      },
      {
        id: "t19",
        title: "Choose materials",
        description: "",
        completed: false,
      },
      { id: "t20", title: "Schedule work", description: "", completed: false },
    ],
  },
];
